---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ansd/main-bosh-docker-build-essential

inputs:
- name: bosh-src
- name: bumped-ruby-release
- name: stemcell

run:
  path: bumped-ruby-release/ci/tasks/test.sh

params:
  RUBY_RELEASE_DIR: ""