ruby-3.1.7.tar.gz:
  size: 20811481
  object_id: ce1c4b21-9435-45db-7142-935f82dcf953
  sha: sha256:0556acd69f141ddace03fa5dd8d76e7ea0d8f5232edf012429579bcdaab30e7b
ruby-3.2.10.tar.gz:
  size: 19983731
  object_id: e945b71a-ff17-443b-7fdc-965444913d5c
  sha: sha256:880acb05e08da8c559c56a13e512bae1b472da67c72ebb750c765f9c2134e689
ruby-3.3.10.tar.gz:
  size: 22233705
  object_id: 1050e99b-4513-42fa-6302-a4f6f28979fa
  sha: sha256:b555baa467a306cfc8e6c6ed24d0d27b27e9a1bed1d91d95509859eac6b0e928
ruby-3.4.8.tar.gz:
  size: 23288284
  object_id: 94de93c3-e587-4fa6-4fa5-83a76165e8e1
  sha: sha256:53c4ddad41fbb6189f1f5ee0db57a51d54bd1f87f8755b3d68604156a35b045b
rubygems-3.3.27.tgz:
  size: 1304416
  object_id: 28f72bfd-ce71-4713-702b-628110f48045
  sha: sha256:dc821bf2a416e9c25a964181a83439209b3ae81cfca1632733ca04da946c0fbd
rubygems-3.4.22.tgz:
  size: 1342799
  object_id: f6b8386f-865a-4a11-5bda-acda3d03eb21
  sha: sha256:803fa77776d11d3d1bb563826616c811124425e0331ad1fd983c4144046a6156
rubygems-3.5.23.tgz:
  size: 960343
  object_id: 453d8361-b53c-429f-5361-7d85e118d891
  sha: sha256:3d277bf0b12ff46834d89b283fc451d130dbe6428d00d7ace4664c449c3ef28c
rubygems-3.6.9.tgz:
  size: 967932
  object_id: 7baea5e3-26bb-4ff9-5fe3-5185b1d9e83b
  sha: sha256:ffdd46c6adbecb9dac561cc003666406efd2ed93ca21b5fcc47062025007209d
yaml-0.2.5.tar.gz:
  size: 609454
  object_id: b5eeae2b-1496-4bc2-556f-efac50c8bcfa
  sha: sha256:c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4
