ruby-3.1.7.tar.gz:
  size: 20811481
  object_id: ce1c4b21-9435-45db-7142-935f82dcf953
  sha: sha256:0556acd69f141ddace03fa5dd8d76e7ea0d8f5232edf012429579bcdaab30e7b
ruby-3.2.9.tar.gz:
  size: 20560944
  object_id: 1a473821-7eb7-4d39-7cb3-07de8ad98028
  sha: sha256:abbad98db9aeb152773b0d35868e50003b8c467f3d06152577c4dfed9d88ed2a
ruby-3.3.10.tar.gz:
  size: 22233705
  object_id: 1050e99b-4513-42fa-6302-a4f6f28979fa
  sha: sha256:b555baa467a306cfc8e6c6ed24d0d27b27e9a1bed1d91d95509859eac6b0e928
ruby-3.4.7.tar.gz:
  size: 23271433
  object_id: 617162f3-ea4c-47e2-6eb2-a7000cb08d9e
  sha: sha256:23815a6d095696f7919090fdc3e2f9459b2c83d57224b2e446ce1f5f7333ef36
rubygems-3.3.27.tgz:
  size: 1304416
  object_id: 28f72bfd-ce71-4713-702b-628110f48045
  sha: sha256:dc821bf2a416e9c25a964181a83439209b3ae81cfca1632733ca04da946c0fbd
rubygems-3.4.22.tgz:
  size: 1342799
  object_id: f6b8386f-865a-4a11-5bda-acda3d03eb21
  sha: sha256:803fa77776d11d3d1bb563826616c811124425e0331ad1fd983c4144046a6156
rubygems-3.5.23.tgz:
  size: 960343
  object_id: 453d8361-b53c-429f-5361-7d85e118d891
  sha: sha256:3d277bf0b12ff46834d89b283fc451d130dbe6428d00d7ace4664c449c3ef28c
rubygems-3.6.9.tgz:
  size: 967932
  object_id: 7baea5e3-26bb-4ff9-5fe3-5185b1d9e83b
  sha: sha256:ffdd46c6adbecb9dac561cc003666406efd2ed93ca21b5fcc47062025007209d
yaml-0.2.5.tar.gz:
  size: 609454
  object_id: b5eeae2b-1496-4bc2-556f-efac50c8bcfa
  sha: sha256:c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4
